config/routes.rb
Rails.application.routes.draw do
  resources :videos
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
  end
  resources :users, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :first_half_score
    validates :second_half_score
    validates :total_score
    validates :golf_course
    validates :date
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :posts
  has_many :comments
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :video, presence: true
has_one_attached :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:golf_history] )
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.create(comment_params)
      redirect_to post_path(@comment.post_id)
  end

private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      redirect_to action: :index
    end
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      render :index
    end
  end

  private

  def post_params
    params.require(:post).permit(:first_half_score, :second_half_score, :total_score, :golf_course, :date, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:user)
    @data = []
    @posts.each do |post|
      @data << [post.date,post.total_score]
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
def index
  @videos = Video.where(user_id:params[:user_id])
end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.save
    redirect_to action: :index
  end

  def show
    #@video = Video.find(params[:id])
  end

  private

  def video_params
    params.require(:video).permit(:introduction, :video).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GNS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("GNS.png", class: :logo), root_path %>
          </div>
           <% if user_signed_in? %>
             <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
               <%= link_to "New Score", new_post_path, class: :nav__btn %>
               <%= link_to "New Video", new_video_path, class: :nav__btn %>
             </div> 
           <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
           <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © GNS All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f|%>
  
  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :date, "日付" %><br />
    <%= f.date_field :date %>
  </div>

  <div class="field">
    <%= f.label :golf_course, "ゴルフ場名" %><br />
    <%= f.text_field :golf_course %>
  </div>

  <div class="score">
   <div>
      <span>スコア</span>
   </div>
   <div class="price-content">
     <div class="price-text">
      <span>IN</span>
     </div>
      <%= f.text_field :first_half_score, class:"price-input", id:"first-score" %>
   </div>
   <div class="price-content">
     <div class="price-text">
      <span>OUT</span>
     </div>
      <%= f.text_field :second_half_score, class:"price-input", id:"second-score" %>
   </div>
   <div class="price-content">
     <span>Total</span>
     <%= f.text_field :total_score, class:"price-input", id:"total-score" %>
   </div>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id)%>
  <div class="card__body">
   <p class="date">
    <%= post.date %>
   </p>
    <%= link_to post.golf_course, 'http://www.par72.co.jp/sp/gc/', class: :card__title%>
    <p class="card__summary">
     <span>IN</span>
      <%= post.first_half_score %>
    </p>
    <p class="card__summary">
     <span>OUT</span>
     <%= post.second_half_score %>
    </p>
    <p class="card__summary">
     <span>Total</span>
     <%= post.total_score %>
    </p>
   <%= link_to post.user.nickname, user_path(post.user.id), class: :card__user %>
  </div>
</div>

app/views/posts/_prototype.html.erb
<div class="card">
  <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "プロトタイプのキャッチコピー" %>
    </p>
    <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">スコア編集</h2>
     <%= render partial: "form"  %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
       <div class="greeting"> 
        <%= "Hello!," %>
        <%= link_to "#{current_user.nickname}さん", user_path(current_user), class: :greeting__link%>
       </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: 'post', collection: @posts %>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">スコア投稿</h2>
      <%= render partial: "form"  %>
    <div>
  </div>
</div>

app/views/posts/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @post.golf_course %>
      </p>
      <%= link_to "by#{@post.user.nickname}", user_path(@post.user_id), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_post_path(@post.id), class: :prototype__btn %>
          <%= link_to "削除する", post_path(@post.id),method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__image">
        <%= image_tag @post.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__message">
            <%= @post.date %>
          </p>
        </div>
        <div class="prototype__detail">
         <p class="detail__title">スコア</p>
          <p class="detail__message">
           <span>IN</span>
           <%= @post.first_half_score %>
          </p>
          <p class="detail__message">
           <span>OUT</span>
           <%= @post.second_half_score %>
          </p>
          <p class="detail__message">
           <span>Total</span>
           <%= @post.total_score %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if current_user %>
          <%= form_with(model: [@post, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <% if @comments %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
               <%= comment.text %>
               <%= link_to comment.user.nickname, user_path(comment.user), class: :comment_user %>
            </li>
            <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "〜マイページ〜" %>
      </h2>
      <%= column_chart @data, width: "200px", height: "300px" %>
    <div class="average_score">
      <span>AVERAGE SCORE</span>
      <%= Post.average(:total_score).floor %>
    </div>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">ゴルフ歴</th>
            <td class="table__col2"><%= @user.golf_history %></td>
          </tr>
          <tr>
            <th class="table__col1">マイムービー</th>
            <td class="table__col2"><%= link_to "ムービー", videos_path(user_id:@user.id) %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
      </div>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="main">
  <div class="inner">
   <div class="form__wrapper">
   <% @videos.each do |video| %>
     <% if video.video.attached? %> 
     <p><%= video.introduction %></p>
     <video src="<%= rails_blob_path(video.video)%>" type="video/mp4" width="500" height="500" controls></video> 
     <% end %>
   <% end %>
   </div>
  </div>
</div>

app/views/videos/new.html.erb
<div class="main">
  <div class="inner">
   <div class="form__wrapper">
    <%= form_with model: @video, local: true do |form| %>
      <p>introduction</p><%= form.text_area :introduction %> <br>
      <p>video</p><%= form.file_field :video %> <br>
    <%= form.submit %>
   <% end %>
   </div>
 </div>
</div>